collection_name: "agent"
persist_directory: "chroma_db"
k: 20
data_path: "data"
md5_hex_store: "md5.txt"
allow_knowledage_file_type: ["txt","pdf"]

chunk_size: 300
chunk_overlap: 80
separators: ["\n\n", "\n", "。", "！", "？", "；", "：", "，", ".", "!", "?", ",", " "]
