main_prompt_path: "prompts/main_prompt.txt"
rag_summarize_prompt_path: "prompts/rag_summarize.txt"
report_prompt_path: "prompts/report_prompt.txt"
refine_query_prompt_path: "prompts/query_rewrite_prompt.txt"
extract_user_query_prompt_path: "prompts/EXTRACT_PROFILE_PROMPT.txt"