main_prompt_path: "prompts/main_prompt.txt"
rag_summarize_prompt_path: "prompts/rag_summarize.txt"
report_prompt_path: "prompts/report_prompt.txt"
refine_query_prompt_path: "prompts/query_rewrite_prompt.txt"
extract_user_query_prompt_path: "prompts/EXTRACT_PROFILE_PROMPT.txt"
select_memoryplan_prompt_path: "prompts/SELECT_MEMORY_PROMPT.txt"
extract_memory_notes_prompt_path: "prompts/extract_memory_notes_prompt"
classify_fact_spans_path: "prompts/split_into_fact_spans.txt"
memory_consolidator_prompt_path: "prompts/MEMORY_CONSOLIDATOR_PROMPT.txt"
memory_note_filter_prompt_path: "prompts/MEMORY_NOTE_FILTER_PROMPT.txt"
ROUTE_QUERY_PROMPT_PATH: "prompts/ROUTE_QUERY_PROMPT.txt"
rag_answer_prompt_path: "prompts/rag_answer_prompt.txt"

