chat_model_name: "Pro/MiniMaxAI/MiniMax-M2.5"
embedding_model_name: "qwen3-embedding:0.6b"
embedding_model_name_silicon: "Qwen/Qwen3-Embedding-8B"
reranking_model_name: "BAAI/bge-reranker-v2-m3"
reranking_model_name_silicon: "Qwen/Qwen3-Reranker-8B"
